site_name: HDX HAPI - The Humanitarian API
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Code Examples: examples.md
  - Data Usage Guide:
      - Affected People: data_usage_guides/affected_people.md
      - Coordination & Context : data_usage_guides/coordination_and_context.md
      - Food Security, Nutrition & Poverty : data_usage_guides/food_security_nutrition_and_poverty.md
      - Geography & Infrastructure : data_usage_guides/geography_and_infrastructure.md
      - Metadata: data_usage_guides/metadata.md
      - Enums: data_usage_guides/enums.md
  - Geo Data: geo.md
  - Changelog: changelog.md
  - Contact: contact.md
theme:
  name: "material"
markdown_extensions:
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - table-reader:
      base_path: "docs_dir"
extra_css:
  - extra.css
