[tool.ruff]
select = ["E", "F", "Q"]

# Allow lines to be as long as 120 characters.
line-length = 120

[tool.ruff.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"

[tool.black]
line-length = 120
skip-string-normalization = true