DOC_ADMIN1_CODE = 'Filter the response by the 1st subnational administrative divisions. The admin1 codes refer to the p-codes in the <a href="https://data.humdata.org/dashboards/cod?">Common Operational Datasets</a>.'
DOC_ADMIN1_NAME = 'Filter the response by the 1st subnational administrative divisions. The admin1 names refer to the <a href="https://data.humdata.org/dashboards/cod?">Common Operational Datasets</a>.'
DOC_ADMIN2_CODE = 'Filter the response by the 2nd subnational administrative divisions. The admin2 codes refer to the p-codes in the <a href="https://data.humdata.org/dashboards/cod?">Common Operational Datasets</a>.'
DOC_ADMIN2_NAME = 'Filter the response by the 1st subnational administrative divisions. The admin2 names refer to the <a href="https://data.humdata.org/dashboards/cod?">Common Operational Datasets</a>.'
DOC_AGE_RANGE_SUMMARY = 'Get the list of age ranges used for disaggregating population data.'
DOC_AGE_RANGE_CODE = 'Filter the response by the age range. These are expressed as [start year]-[end year]. The end year is assumed to be inclusive, though that is not always explicit in the source data.'
DOC_HDX_DATASET_ID = 'A unique identifier of a Dataset on HDX. Datasets contain one or more resources, which are the sources of the data found in HAPI. Most of the metadata is found at the dataset level.'
DOC_HDX_DATASET_NAME = 
DOC_LOCATION_CODE = 'Filter the response by a location (typically a country). The location codes use the ISO-3 (ISO 3166 alpha-3) codes.'
DOC_LOCATION_NAME = 'Filter the response by a location (typically a country). The location names are based on the "short name" from the <a href="https://unstats.un.org/unsd/methodology/m49/#fn2">UN M49 Standard</a>.'
DOC_SCOPE_DISCLAIMER = 'Not all data are available for all locations. Learn more about the scope of data coverage in HAPI in the <a href="https://FIXTHIS/">Overview and Getting Started</a> documentation.'
DOC_SEE_ADMIN1 = 'See the <a href="https://FIXTHIS/docs#/Location%20and%20Administrative%20Divisions/get_admin1_api_admin1_get">admin1 endpoint</a> for details.'
DOC_SEE_ADMIN2 = 'See the <a href="https://FIXTHIS/docs#/Location%20and%20Administrative%20Divisions/get_admin2_api_admin2_get">admin2 endpoint</a> for details.'
DOC_SEE_LOC =  'See the <a href="https://FIXTHIS/docs#/Location%20and%20Administrative%20Divisions/get_locations_api_location_get">location endpoint</a> for details.'