DOC_ADMIN1_CODE = 'Filter the response by the 1st subnational administrative divisions. The admin1 codes refer to the p-codes in the <a href="https://data.humdata.org/dashboards/cod?">Common Operational Datasets</a>.'
DOC_ADMIN1_NAME = 'Filter the response by the 1st subnational administrative divisions. The admin1 names refer to the <a href="https://data.humdata.org/dashboards/cod?">Common Operational Datasets</a>.'
DOC_ADMIN2_CODE = 'Filter the response by the 2nd subnational administrative divisions. The admin2 codes refer to the p-codes in the <a href="https://data.humdata.org/dashboards/cod?">Common Operational Datasets</a>.'
DOC_ADMIN2_NAME = 'Filter the response by the 1st subnational administrative divisions. The admin2 names refer to the <a href="https://data.humdata.org/dashboards/cod?">Common Operational Datasets</a>.'
DOC_AGE_RANGE_SUMMARY = 'Get the list of age ranges used for disaggregating population data'
DOC_AGE_RANGE_CODE = 'Filter the response by the age range. These are expressed as [start year]-[end year]. The end year is assumed to be inclusive, though that is not always explicit in the source data.'
DOC_GENDER_SUMMARY = 'Get the list of gender codes used for disaggregating population data'
DOC_GENDER_CODE = 'Filter the response by the gender code.'
DOC_GENDER_DESCRIPTION = 'Filter the response by the gender description.'
DOC_HDX_DATASET_ID = 'Filter the response by the dataset ID, which is a unique and fixed identifier of a Dataset on HDX. A URL in the pattern of `https://data.humdata.org/dataset/[dataset id]` will load the dataset page on HDX.'
DOC_HDX_DATASET_NAME = 'Filter the response by the URL-safe name of the dataset as displayed on HDX. This name is unique but can change. A URL in the pattern of `https://data.humdata.org/dataset/[dataset name]` will load the dataset page on HDX.'
DOC_HDX_DATASET_TITLE = 'Filter the response by the title of the dataset as it appears in the HDX interface. This name is not unique and can change.'
DOC_HDX_PROVIDER_STUB = 'Filter the response by the code of the provider of the dataset on HDX. A URL in the pattern of `https://data.humdata.org/organization/[org stub]` will load the provider\'s page on HDX.'
DOC_HDX_PROVIDER_NAME = 'Filter the response by the display name of the provider of the dataset on HDX.'
DOC_HDX_RESOURCE_ID = 'Filter the response by the resource ID, which is a unique and fixed identifier of a Dataset on HDX. A URL in the pattern of `https://data.humdata.org/dataset/[dataset id]/resource/[resource id]` will load the dataset page on HDX.'
DOC_HDX_RESOURCE_FORMAT = 'Filter the response by the format of the resource on HDX. These are typically file formats, but can also include APIs and web apps.'
DOC_HDX_RESOURCE_HXL = 'Filter the response by whether or not the resource contains <a href="https://hxlstandard.org/">HXL tags</a>.'
DOC_LOCATION_CODE = 'Filter the response by a location (typically a country). The location codes use the ISO-3 (ISO 3166 alpha-3) codes.'
DOC_LOCATION_NAME = 'Filter the response by a location (typically a country). The location names are based on the "short name" from the <a href="https://unstats.un.org/unsd/methodology/m49/#fn2">UN M49 Standard</a>.'
DOC_ORG_ACRONYM = 'Filter the response by the standard acronym used to represent the organization. When data is brought into the HAPI database, an attempt is made to standardize the acronyms.'
DOC_ORG_NAME = 'Filter the response by the standard name used to represent the organization. When data is brought into the HAPI database, an attempt is made to standardize the acronyms.'
DOC_ORG_TYPE_CODE = 'Filter the response by the organization type code.'
DOC_ORG_TYPE_DESCRIPTION = 'Filter the response by the organization type description.'
DOC_SCOPE_DISCLAIMER = 'Not all data are available for all locations. Learn more about the scope of data coverage in HAPI in the <a href="https://FIXTHIS/">Overview and Getting Started</a> documentation.'
DOC_SECTOR_CODE = 'Filter the response by the sector code.'
DOC_SECTOR_NAME = 'Filter the response by the sector name.'
DOC_UPDATE_DATE_MIN = 'Min date of update date, e.g. 2020-01-01 or 2020-01-01T00:00:00'
DOC_UPDATE_DATE_MAX = 'Max date of update date, e.g. 2020-01-01 or 2020-01-01T00:00:00'

DOC_SEE_ADMIN1 = 'See the <a href="https://FIXTHIS/docs#/Location%20and%20Administrative%20Divisions/get_admin1_api_admin1_get">admin1 endpoint</a> for details.'
DOC_SEE_ADMIN2 = 'See the <a href="https://FIXTHIS/docs#/Location%20and%20Administrative%20Divisions/get_admin2_api_admin2_get">admin2 endpoint</a> for details.'
DOC_SEE_DATASET = 'See the <a href="https://FIXTHIS/docs#/HDX%20Metadata/get_datasets_api_dataset_get">dataset endpoint</a> for details.'
DOC_SEE_LOC =  'See the <a href="https://FIXTHIS/docs#/Location%20and%20Administrative%20Divisions/get_locations_api_location_get">location endpoint</a> for details.'
DOC_SEE_ORG_TYPE = 'See the <a href="https://FIXTHIS/docs#/humanitarian-response/get_org_types_api_org_type_get">org type endpoint</a> for details.'