name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the docker-compose stack
        run: |
          cd docker
          docker-compose up -d

      - name: Install requirements
        run: |
          cd docker
          docker-compose exec -T hapi sh -c "apk add git"
          docker-compose exec -T hapi sh -c "pip install --upgrade --force-reinstall -r requirements.txt"
          docker-compose exec -T hapi sh -c "pip install --upgrade --force-reinstall -r dev-requirements.txt"

      - name: Setup database
        run: | 
          ./initialize_test_db.sh

      - name: Test with pytest
        run: |
          cd docker
          docker-compose exec -T hapi sh -c "pytest --log-level=INFO --cov=. --cov-report term --cov-report xml:coverage.xml"

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
